[#patterns]
= Patterns and Recipes

Included are a series of patterns and examples of Publishers, Subscribers, and pipelines.
These examples are meant to illustrate how to use the Combine framework to accomplish various tasks.

[NOTE]
====
__Since this is a work in progress:__
if you have a suggestion for a pattern or recipe, I'm happy to consider it.

Please https://github.com/heckj/swiftui-notes/issues/new/choose[Open an issue] in GitHub to request something.
====

[#patterns-creating-subscriber]
== Pattern 1: Creating a subscriber with sink

If you are creating the subscriber, you can use `.sink()`` to receive and process this information.
The simplest form of `.sink()` takes a single closure - but by default this is the closure that receives data (if provided by the pipeline).
If you don't also include a closure to get the completion, you will not receive any information about failures.

[WARNING]
====
Remember that subscribers drive the execution of any Combine pipelines you create.
If you end a pipeline with `.sink()` you are creating the subscriber and connecting it to the pipeline.
By chaining it, it will implicitly start <<coreconcepts.adoc#core-lifecycle,the lifecycle>> with the `subscribe` and request for unlimited data.
====


A simple sink is created with a single closure:

[source, swift]
----
let _ = remoteDataPublisher.sink { value in
    print(".sink() received \(String(describing: value))")
}
----

The closure gets invoked for every new update that the publisher creates, up until the completion.
If an error or failure occurs, then the closure will simply never be called.

When you write the closure for a `sink` subscriber, be aware that your receiveValue closure may be called repeatedly.
How often it is called depends on the pipeline to which it is subscribing.

If you are creating a subscriber and want to receive and handle failures, or see the completion messages at the end of pipeline, create a sink with two closures.
The more complete sink has the two closures named`receiveCompletion` and `receiveValue`:

[source, swift]
----
let _ = remoteDataPublisher.sink(receiveCompletion: { err in
    print(".sink() received the completion", String(describing: err))
}, receiveValue: { value in
    print(".sink() received \(String(describing: value))")
})
----

The type that is passed into receiveCompletion is the enum https://developer.apple.com/documentation/combine/subscribers/completion[`Subscribers.Completion`].
The completion `.failure` incudes an Error within it, which provides access to the underlying cause of the failure.
If you want to get to the error in the subscriber, you can `switch` on the returned completion to determine if it is `.finished` or `.failure`, and then pull out the error:

[#source-with-inline-comments]
[source, swift]
----
.sink(receiveCompletion: { completion in
    switch completion {
    case .finished:
        // no associated data, but you can react to knowing the request has been completed
        break
    case .failure(let anError):
        // do what you want with the error details, presenting, logging, or hiding as appropriate
        print("GOT THE ERROR: ", anError)
        break
    }
}, receiveValue: { someValue in
    // do what you want with the resulting value passed down
    // be aware that depending on the data type being returned, you may get this closure invoked
    // multiple times.
    print(".sink() received \(someValue)")
})
----

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-dataTaskPublisher-decode]
== Pattern 2: Making a network request with dataTaskPublisher

One of the common use cases is requesting JSON data from a URL and decoding it.
This can be readily accomplished with Combine using https://developer.apple.com/documentation/foundation/urlsession/3329708-datataskpublisher[dataTaskPublisher] on https://developer.apple.com/documentation/foundation/urlsession[URLSession].
The data that is returns down the pipeline is a tuple: `(data: Data, response: URLResponse)`

The simplest case of using this might be:

[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .map({ (inputTuple) -> Data in
        return inputTuple.data
    })
    .decode(type: IPInfo.self, decoder: JSONDecoder())
    .eraseToAnyPublisher()
----

With this example, the subscriber will get an instance of the struct IPInfo or will receive a completion notification with an error.
The dataTaskPublisher makes a single request, and what you build in the pipeline will determine what the subscriber receives.

A failed URL request will result in a `.failure` completion with an encapsulated error.
Likewise, if the returned data couldn't be decoded based on the structure, or wasn't JSON, then the result will be a `.failure` completion with an encapsulated decoding error from the decoder.

To have more control over what is considered a failure in the URL response, use a `tryMap` operator on the tuple response from dataTaskPublisher.
An example of that might look like:

[#source-with-exterior-description]
[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

enum testFailureCondition: Error {
    case invalidServerResponse
}

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .tryMap { data, response -> Data in
        // this give you the full capability to react to both the data and the HTTPURLResponse
        // with the expectation that you will throw an error if a failure completion is warranted.
        guard let httpResponse = response as? HTTPURLResponse,
            // this will casue an .failure completion on anything other than a 200 response
            httpResponse.statusCode == 200 else {
                throw testFailureCondition.invalidServerResponse
        }
        return data
    }
    .decode(type: IPInfo.self, decoder: JSONDecoder())
    .eraseToAnyPublisher()
----

The above example uses tryMap to allow for an error to be thrown within the closure.
This lets you put in logic that inspects the specific status code, or you could inspect the data prior to sending it into `JSONDecoder`.

When an error is triggered on the pipeline, a `.failure` completion is sent with the error encapsulated within it, regardless of where it happened in the pipeline.

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-general-error-handling]
== Pattern 3: Handling errors within the pipline

The examples above expected that the subscriber would handle the error conditions, if they occured.
However, you are not always able to control the subscriber - as might be the case if you're using SwiftUI view properties as the subscriber, and you're providing the publisher.
In these cases, you need to build your pipeline so that the output types match the subscriber types.

For example, if you are working with SwiftUI and the you want to use `.assign` to set the `isEnabled` property on a button, the subscriber will have a few requirements:

. the subcriber should match the type output of `<Bool>`, `<Never>`
. the subscriber should be called on the main thread

With a publisher that can throw an error (such as `dataTaskPublisher`), you need to construct a pipeline to convert the output type, but also handle the error within the pipeline to match a failure type of `<Never>`.

How you handle the errors within a pipeline is very dependent on how the pipeline is working.
If the pipeline is set up to return a single result and terminate, continue to <<patterns-oneshot-error-handling>>.
If the pipeline is set up to continually update, the error handling needs to be a little more complex.
Jump ahead to <<patterns-continual-error-handling>>.

[#patterns-assertNoFailure]
=== converting to a Never failure type using assertNoFailure

A brutal way to handle this is to crash the application when an error happens.
Combine provides the operator `assertNoFailure()` for this purpose.
This is useful if you are sure you handled the errors and need to map a pipeline which technically can generate a failure type of `<Error>` to a subscriber that requires a failure type of `<Never>`.

Adding it into the pipeline requires no additional parameters, but you can include a string:

[source, swift]
----
.assertNoFailure()
// OR
.assertNoFailure("What could possibly go wrong?")
----

[NOTE]
====
I'm not entirely clear on where that string would appear if you did include it.

When trying out this code in unit tests, the tests invariably drop into a debugger at the assertion point when a .failure is processed through the pipeline.
====

It is far more likely that you want to handle the error and not have the application crash.

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-oneshot-error-handling]
== Pattern 3.1: Using catch to handle errors in a one-shot pipeline

The `.catch()` operator is useful to recover from an error, but it can have unexpected side effects if you aren't familiar with how it works.
`.catch()` handles errors by replacing the upstream publisher with another publisher that you provide as a return in a closure.
This effectively terminates the earlier portion of the pipeline.
If you're using a one-shot publisher (one that doesn't create more than a single event), then this is fine.

For example, dataTaskPublisher is a one-shot publisher, and you might use catch with it to ensure that you get a response, returning a placeholder in the event of an error.
Extending our previous example to provide a default response:

[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .map({ (inputTuple) -> Data in
        return inputTuple.data
    })
    .decode(type: IPInfo.self, decoder: JSONDecoder())
    .catch { err in
        return Publishers.Just(IPInfo(ip: "8.8.8.8"))
    }
    .eraseToAnyPublisher()
----

Now the `remoteDataPublisher` can be used with

[source, swift]
----
.receive(on: RunLoop.main)
.assign(to: \.isEnabled, on: yourButton)
----

[NOTE]
====
It's worth mentioning that there is also a `tryCatch()` operator, which supports you doing your own analysis on the error and potentially throwing a new/different failure condition down the chain.
Like `catch()` it also replaces the publisher.
====

// NOTE(heckj): this next bit (until retry) might be better migrated to the reference section on how catch works.

A possible problem with this technique is that the if the original publisher generates more values to which you wish to react, the original pipeline has been ended.
This means if you are creating a pipeline that reacts to a `@Published` property, then after any failed value that activates the catch operator, the pipeline will cease to react further.
See <<reference.adoc#reference-catch>> for more detail and an example.

[#patterns-retry]
=== retrying in the event of a temporary failure

The `retry` operator can be included in a chain to retry a subscription when a `.failure` completion occurs.
When you specify this operator in a pipeline and it receives a subscription, it first tries to request a subscription from it's upstream publisher.
If the response to that subscription fails, then it will retry the subscription to the same publisher.

The retry operator can be specified with a number of retries to attempt.
If no number of retries is specified, it will attempt to retry indefinitely until it receives a .finished completion from it's subscriber.
If the number of retries is specified and all requests fail, then the `.failure` completion is passed down to the subscriber of this operator.

In practice, this is mostly commonly desired when attempting to request network resources with an unstable connection.
If you use a retry operator, you should add a specific number of retries so that the subscription doesn't effectively get into an infinite loop.

An example of the above example using retry:

[source, swift]
----
struct IPInfo: Codable {
    // matching the data structure returned from ip.jsontest.com
    var ip: String
}
let myURL = URL(string: "http://ip.jsontest.com")
// NOTE(heckj): you'll need to enable insecure downloads in your Info.plist for this example
// since the URL scheme is 'http'

let remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: myURL!)
    // the dataTaskPublisher output combination is (data: Data, response: URLResponse)
    .retry(3)
    // if the URLSession returns a .failure completion, try at most 3 times to get a successful response
    .map({ (inputTuple) -> Data in
        return inputTuple.data
    })
    .decode(type: IPInfo.self, decoder: JSONDecoder())
    .catch { err in
        return Publishers.Just(IPInfo(ip: "8.8.8.8"))
    }
    .eraseToAnyPublisher()
----

[WARNING]
====
When using the `retry()` operator with `dataTaskPublisher`, verify that the URL you are requesting isn't going to have negative side effects if requested repeatedly or with a retry.
Ideally such requests are be expected to be idempotent.
====

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-continual-error-handling]
== Pattern 3.2: Using flatMap with catch to handle errors

The `flatMap()` operator is exactly what we need in this use case.

You can think of the `flatMap()` operator as a way to inject values into your pipeline from a temporary one-shot publisher.
For every element `flatMap()` receives, it invokes it's closure to create a publisher.
That publisher is then sending values to any downstream subscriber.

This is a perfect mechanism for when you want to maintain updates up an upstream publisher, as it effectively creates one-shot publishers (or even small pipelines) that send a single value and then complete.
The completion from the created one-shot publishers terminates in the flatMap and isn't passed to downstream subscribers.
To use this with error handling, we can create a one-shot publisher, or pipeline, that starts with the value provided upstream.
Then we create the pipeline to do any potentially failing work, and construct it with a `.catch` as we saw earlier to provide a fallback value.

A diagram version of this pipelines might be:

[source]
----
     one-shot-publisher(value) -> catch ( fallback )      // <- one-shot pipeline
                          ^                        \
                          |                         \
publisher -> flatMap -> ( +                           +  ) -> subscriber
----

In swift, this looks like:

[source, swift]
----
.flatMap { data in
    return Just(data)
    .decode(YourType.self, JSONDecoder())
    .catch {
        return Just(YourType.placeholder)
    }
}
----

// force a page break - in HTML rendering is just a <HR>
<<<

== Pattern 4: Requesting data from an alternate URL when the network is constrained

From Apple's WWDC 19 presentation https://developer.apple.com/videos/play/wwdc2019/712/[Advances in Networking, Part 1], a sample pattern was provided using `.tryCatch` and `.tryMap` operators to react to the specific error of having the network be constrained.

[source, swift]
----
// Generalized Publisher for Adaptive URL Loading
func adaptiveLoader(regularURL: URL, lowDataURL: URL) -> AnyPublisher<Data, Error> {
    var request = URLRequest(url: regularURL)
    request.allowsConstrainedNetworkAccess = false
    return URLSession.shared.dataTaskPublisher(for: request)
        .tryCatch { error -> URLSession.DataTaskPublisher in
            guard error.networkUnavailableReason == .constrained else {
               throw error
            }
            return URLSession.shared.dataTaskPublisher(for: lowDataURL)
        .tryMap { data, response -> Data in
            guard let httpResponse = response as? HTTPUrlResponse,
                   httpResponse.status_code == 200 else {
                       throw MyNetworkingError.invalidServerResponse
            }
            return data
}
.eraseToAnyPublisher()
----

In the sample, if the error returned from the original request wasn't an issue of the network being constrained, it passes on the .failure completion down the pipeline.
If the error is that the network is constrained, then the tryCatch operator creates a new request to an alternate URL.

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-update-interface-network-request]
== Pattern 5: Update the status of your interface from a network request

Below is a contrived example where you want to make a network to check for the username availability that you are watching with `@Published`.
As the property `username` is updated, you want to check to see if the updated username is available.

This contrived example expects that you have a web service that you can query, which will return a structured response in JSON.

[source, swift]
----
@Published var username: String = ""

struct UsernameResponse: Codable {
    username: String
    available: Bool
}

var validatedUsername: AnyPublisher<String?, Never> {
    return $username
        .debounce(for: 0.5, scheduler: RunLoop.main)
        .removeDuplicates()
        .flatMap { username in
            let constructedURL = URL(string: "https://yourhost.com/?user=\(username)")
            return remoteDataPublisher = URLSession.shared.dataTaskPublisher(for: constructedURL!)
                .map({ (inputTuple) -> Data in
                    return inputTuple.data
                })
                .decode(type: UsernameResponse.self, decoder: JSONDecoder())
                .map { response: UsernameResponse in
                    return response.available
                }
                .catch { err in
                    // if the service is down, or the JSON malformed, return a false response
                    return Publishers.Just(False))
                }
        }
}
----

In the example above, for every update into .flatMap() we are creating a request to check and parse for the availability from the service.

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-sequencing-async]
== Pattern 6: Coordinating a sequence of asynchronous operations

There are a variety of ways to chain together asynchronous operations.
Combine adds to this variety, and is effective when you want to use the data from one operation as the input to the next.
If you are familiar with using Promises in another language, such as Javascript, this pattern is roughly the equivalent of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Chaining[Promise chaining].

The benefit to using Combine is that the sequencing can be relatively easy to parse visually.

=== Using Future to turn an an asynchronous call into publisher

[source, swift]
----

let myPublisher = Publishers.Future { promise in
    asyncFunctionWithACompletion(inputValue) { outputValue in
        promise(.success(outputValue ? inputValue : nil))
    }
}
.eraseToAnyPublisher()
----

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-binding]
== Pattern 8: binding

* binding to SwiftUI
** validating forms
** UX responsiveness - live updates to view properties
** handling error within property update
** retry for remote service

simple case - data validation with external service

[source, swift]
----
@Published var username: String = ""

var validatedUsername: AnyPublisher<String?, Never> {
    return $username
        .debounce(for: 0.5, scheduler: RunLoop.main)
           //  <String?>|<Never>
        .removeDuplicates()
           //  <String?>|<Never>
        .flatMap { username in
            return Future { promise in
                self.usernameAvailable(username) { available in
                   promise(.success(available ? username : nil))
                }
          //    <Result<Output, Failure>>
            }
        }
          // <String?>|<Never>
        .eraseToAnyPublisher()
}
----

validation - listening for changes to validate them together

[source, swift]
----
@Published var password: String = ""
@Published var passwordAgain: String = ""

var validatedPassword: AnyPublisher<String?, Never> {
    return CombineLatest($password, $passwordAgain) { password, passwordAgain in
        guard password == passwordAgain, password.count > 8 else { return nil }
        return password
    }
      //  <String?>|<Never>
    .map { $0 == password1 ? nil : $0 }
      //  <String?>|<Never>
    .eraseToAnyPublisher()
      //  <String?>|<Never>
}
----

more complex validation - bringing together substreams

[source, swift]
----
var validatedCredentials: AnyPublisher<(String, String)?, Never> {
    return CombineLatest(validatedUsername, validatedPassword) { username, password in
        guard let uname = username, let pwd = password else { return nil }
        return (uname, pwd)
    }
    .eraseToAnyPublisher()
}

@IBOutlet var signupButton: UIButton!

var signupButtonStream: AnyCancellable?

override func viewDidLoad() {
    super.viewDidLoad()
    self.signupButtonStream = self.validatedCredentials
        .map { $0 != nil }
        .receive(on: RunLoop.main)
        .assign(to: \.isEnabled, on: signupButton)
}
----

// force a page break - in HTML rendering is just a <HR>
<<<

[#patterns-testing]
== Pattern N: Testing pipelines

a few test strategies...

For testing what's happening in a pipeline:

* use a Subject -> pipeline -> sink()
* set up a sink to collect value
* drive values through the pipeline with Subject.send()
* assert results after the sink has processed them

For testing a publisher (and any pipeline attached)

* set up an expectation (`XCTestExpectation`)
* create your publisher & relevant pipeline if so desired
* create a sink to capture the results that works on both completions and values
** this can be separate, or just chained to the pipeline, depending on what makes most sense to you
* `wait` on the expectation to let the test "do it's thing" in the background

For testing a subscriber (how it reacts):

* set up your subscriber and any pipeline leading to it
* use a Subject to "inject" values
* test the results after the value is sent
* if the updates include some async/background work before data is available, use an expectation
** add a callback to the async pieces where you can trigger the expectation, and do your asserts just prior to fulfilling the expectation

& of course you can always test using UITesting - spinning up your whole app, initializing state, and then driving and verifying the results.

__(Uncertain)__ Mocking or faking a publisher (such as dataTaskPublisher) to validate things like using `retry()` operator
* might be able to use a `Publishers.Future()`, expose as an AnyPublisher() (do the same with dataTaskPublisher) to make the the same - and in your setup, inject in the one you want to use.
** Instrument the Future() closure to record what gets called, and maybe set it up to return an explicit set of responses.

[#patterns-debugging]
== Pattern N+1: Debugging pipelines

. use print() and/or print("prefixValue") to get console output of what's happening in the pipeline lifecycle
  * create a .sink() to capture results, and drive it with a PassthroughSubject for specific control

. add a handleEvents() operator
  * create closures to do additional poking at values or digging into more structured pieces than get exposed with a print()
  * allows you to ignore some sections you don't care about
  * closures on `receiveSubscription`, `receiveRequest`, `receiveCancel`, `receiveOutput`, and `receiveCompletion`

. breakPoint
  * if you want to break into a debugger, add in a closure that returns true and you can inspect to your heart's content
  ** closure's on `receiveSubscription`, `receiveOutput`, and `receiveCompletion`

  * might also be interesting to use breakpointOnError() which triggers only when a failure completion


// force a page break - in HTML rendering is just a <HR>
<<<
